name: Cachix

on:
  push:
    branches:
      - master
  workflow_dispatch:
    inputs:
      deploy:
        description: "Deploy after the build"
        type: boolean
        default: true
        required: true

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  cachix:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3.1.0
      - uses: cachix/install-nix-action@v18
        with:
          extra_nix_config: |
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
      - uses: cachix/cachix-action@v12
        with:
          name: playernamehere-nixos
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
          extraPullNames: nix-gaming, hyprland, nix-community, devenv
      - name: Check
        run: nix flake check
      - name: Build
        run: nix build --print-build-logs .#cachix-deploy-spec
      - name: Deploy
        if: github.event_name == 'workflow_dispatch' && github.event.inputs.deploy
        env:
          CACHIX_ACTIVATE_TOKEN: "${{ secrets.CACHIX_ACTIVATE_TOKEN }}"
        run: |
          cachix push playernamehere-nixos ./result
          cachix deploy activate ./result
