name: Cachix

on:
  pull_request:
  workflow_dispatch:

jobs:
  cachix:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3.1.0
      - uses: cachix/install-nix-action@v18
        with:
          extra_nix_config: |
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
      - uses: cachix/cachix-action@v12
        with:
          name: playernamehere-nixos
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
          extraPullNames: nix-gaming, hyprland, nix-community
      - run: nix build .#nixosConfigurations.shiba-asus.config.system.build.toplevel
