---
name: Cachix

on:
  push:
    branches-ignore:
      - update-flake-inputs-and-npins
  pull_request:
  workflow_dispatch:
    inputs:
      deployments:
        description: |
          JSON array of machines to deploy to.
          Each machine should be represented by its hostname.
          For example, `[ "alpha", "bravo" ]`.
        type: string

run-name: ${{ inputs.deployments != '' && 'Deploy NixOS configuration' || 'Build flake outputs' }}

# Builds and deployments are in separate concurrency groups.
# Builds can cancel other in-progress builds on the same ref.
# Deployments will not cancel other in-progress deployments (but will cancel existing pending deployments),
# no matter what ref.
concurrency:
  group: ${{ github.workflow }}-${{ inputs.deployments != '' && 'deploy' || 'build' }}${{ inputs.deployments != '' && '' || format('-{0}', github.ref) }}
  cancel-in-progress: ${{ inputs.deployments == '' }}

env:
  NIX_CACHE_PATH: /tmp/nixcache
  CACHIX_CACHE: "playernamehere-nixos"

jobs:
  check-flake:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3.1.0
      - uses: cachix/install-nix-action@v20
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Check flake
        run: nix flake check --keep-going --impure  # devenv requires impure
  generate-deploy-spec-matrix:
    runs-on: ubuntu-22.04
    needs: [check-flake]
    outputs:
      matrix: ${{ steps.generate.outputs.matrix }}
      cache-key: ${{ steps.generate.outputs.cache-key }}
    steps:
      - uses: actions/checkout@v3.1.0
      - uses: cachix/install-nix-action@v20
        with:
          extra_nix_config: |
            extra-substituters = https://playernamehere-nixos.cachix.org https://nix-gaming.cachix.org https://hyprland.cachix.org https://nix-community.cachix.org https://devenv.cachix.org
            extra-trusted-public-keys = playernamehere-nixos.cachix.org-1:oUHiXCIHbB+VbjDIlckfjwaYkJEvpkW3250+FhF5Vi4= nix-gaming.cachix.org-1:nbjlureqMbRAxR1gJ/f3hxemL9svXaZF/Ees8vCUUs4= hyprland.cachix.org-1:a7pgxzMz7+chwVL3/pzj6jIBMioiJM7ypFP8PwtkuGc= nix-community.cachix.org-1:mB9FSh9qf2dCimDSUo8Zy7bkq5CX+/rkCWyvRCYg3Fs= devenv.cachix.org-1:w1cLUi8dv3hnoSPGAuibQv+f9TZLr6cv/Hm9XgU50cw=
      - id: generate
        name: Generate matrix of deploy specs
        env:
          DEPLOYMENTS: ${{ inputs.deployments }}
        run: |
          matrix=$(nix develop .#ci --impure --command generate-deploy-spec-matrix.sh . "$DEPLOYMENTS")
          printf '%s' "matrix=$matrix" >> "$GITHUB_OUTPUT"

          cache_key=$(nix develop .#ci --impure --command generate-cache-key.sh <<<"$matrix")
          printf '%s' "cache-key=$cache_key" >> "$GITHUB_OUTPUT"
      - name: Export Nix store cache  # https://github.com/cachix/install-nix-action/issues/56#issuecomment-1300421537
        run: nix copy --no-check-sigs --all --to "${{ env.NIX_CACHE_PATH }}"
      - uses: actions/cache/save@v3
        with:
          path: ${{ env.NIX_CACHE_PATH }}
          key: ${{ steps.generate.outputs.cache-key }}
  build-deploy-specs:
    runs-on: ubuntu-22.04
    needs: [generate-deploy-spec-matrix]
    strategy:
      fail-fast: false
      matrix:
        deploy-spec: ${{ fromJson(needs.generate-deploy-spec-matrix.outputs.matrix) }}
    steps:
      - id: check-deploy-spec-artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          name: ${{ matrix.deploy-spec.hashName }}
          workflow_conclusion: ""
          search_artifacts: true
          if_no_artifact_found: ignore
      - name: Free up space
        # Unfortunately, all outputs are Unicode strings, so `fromJSON` must be used
        # whenever referencing this output to properly convert it to a boolean
        # https://github.com/actions/runner/issues/2238#issuecomment-1318973310
        # https://docs.github.com/en/actions/using-jobs/defining-outputs-for-jobs
        if: ${{ !fromJSON(steps.check-deploy-spec-artifact.outputs.found_artifact) }}
        run: |
          # Taken from https://github.com/easimon/maximize-build-space/blob/67afc2d7662c9d296547435e7605cc57a1df46f3/action.yml#L110
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /opt/ghc
          sudo rm -rf /usr/local/lib/android
          sudo rm -rf /opt/hostedtoolcache/CodeQL
          sudo docker image prune --all --force
      - if: ${{ !fromJSON(steps.check-deploy-spec-artifact.outputs.found_artifact) }}
        uses: cachix/install-nix-action@v20
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
          extra_nix_config: |
            # `i686-linux` must be present for 32-bit software
            # More context: https://github.com/NixOS/nixpkgs/issues/86506#issuecomment-623746883
            extra-platforms = i686-linux aarch64-linux
      - if: ${{ !fromJSON(steps.check-deploy-spec-artifact.outputs.found_artifact) }}
        uses: cachix/cachix-action@v12
        with:
          name: ${{ env.CACHIX_CACHE }}
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
          extraPullNames: "nix-gaming, hyprland, nix-community, devenv"
          skipPush: true  # `cachix watch-store` is used below, so this is not needed
      - if: ${{ !fromJSON(steps.check-deploy-spec-artifact.outputs.found_artifact) }}
        uses: actions/cache/restore@v3  # https://github.com/cachix/install-nix-action/issues/56#issuecomment-1300421537
        with:
          path: ${{ env.NIX_CACHE_PATH }}
          key: ${{ needs.generate-deploy-spec-matrix.outputs.cache-key }}
          fail-on-cache-miss: true
      - if: ${{ !fromJSON(steps.check-deploy-spec-artifact.outputs.found_artifact) }}
        name: Import Nix store cache
        run: nix copy --no-check-sigs --from ${{ env.NIX_CACHE_PATH }} --all
      - if: ${{ !fromJSON(steps.check-deploy-spec-artifact.outputs.found_artifact) }}
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: "arm64"  # Required to build `bravo` since it is `aarch64`
      - if: ${{ !fromJSON(steps.check-deploy-spec-artifact.outputs.found_artifact) }}
        uses: actions/checkout@v3
      - if: ${{ !fromJSON(steps.check-deploy-spec-artifact.outputs.found_artifact) }}
        name: Watch store and push new paths to binary cache
        run: cachix watch-store ${{ env.CACHIX_CACHE }} &
      - if: ${{ !fromJSON(steps.check-deploy-spec-artifact.outputs.found_artifact) }}
        name: Build `${{ matrix.deploy-spec.drvPath }}`
        run: nix build --print-build-logs ${{ matrix.deploy-spec.drvPath }}
      - if: ${{ !fromJSON(steps.check-deploy-spec-artifact.outputs.found_artifact) }}
        name: Push result to binary cache
        run: cachix push ${{ env.CACHIX_CACHE }} ./result
      - if: ${{ !fromJSON(steps.check-deploy-spec-artifact.outputs.found_artifact) }}
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.deploy-spec.hashName }}
          path: ./result
  deploy:
    runs-on: ubuntu-22.04
    needs: [generate-deploy-spec-matrix, build-deploy-specs]
    if: ${{ github.event_name == 'workflow_dispatch' && inputs.deployments != '' }}
    strategy:
      fail-fast: false
      matrix:
        deploy-spec: ${{ fromJson(needs.generate-deploy-spec-matrix.outputs.matrix) }}
    steps:
      - id: download-deploy-spec-artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          name: ${{ matrix.deploy-spec.hashName }}
          workflow_conclusion: ""
          search_artifacts: true
      - uses: cachix/install-nix-action@v20
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      - uses: cachix/cachix-action@v12
        with:
          name: playernamehere-nixos
          skipPush: true
      - name: Deploy
        env:
          CACHIX_ACTIVATE_TOKEN: "${{ secrets.CACHIX_ACTIVATE_TOKEN }}"
        run: |
          cachix deploy activate ./result
