name: Update

on:
  schedule:
    - cron: '0 0 1,15 * *' # run on the 1st and 15th of every month
  workflow_dispatch:

jobs:
  update-flake:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3.1.0
        with:
          ref: ${{ github.ref }}
      - uses: cachix/install-nix-action@v19
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Update flake inputs
        run: nix flake update
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "chore(flake): update inputs"
  generate-npins-matrix:
    runs-on: ubuntu-22.04
    outputs:
      npins-matrix: ${{ steps.npins-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v3.1.0
      - id: npins-matrix
        name: Generate npins matrix
        run: |
          # Outputs a list of { "name": <pin-name>, "npins-dir": <dir> }
          filter='include "npins_matrix"; (.[0] | npins_matrix("pkgs/npins")) + (.[1] | npins_matrix("pkgs/vim-plugins/npins"))'
          matrix=$(jq -c -s -L .github/workflows "$filter" pkgs/npins/sources.json pkgs/vim-plugins/npins/sources.json)
          printf '%s' "matrix=$matrix" >> "$GITHUB_OUTPUT"
  update-npins:
    needs: [generate-npins-matrix, update-flake]
    if: ${{ needs.generate-npins-matrix.result == 'success' && needs.generate-npins-matrix.outputs.npins-matrix != '[]' }}
    strategy:
      fail-fast: false
      max-parallel: 1
      matrix:
        pin: ${{ fromJson(needs.generate-npins-matrix.outputs.npins-matrix) }}
    uses: ./.github/workflows/update-npins.yml
    with:
      npins_dir: ${{ matrix.pin.npins-dir }}
      pin: ${{ matrix.pin.name }}
